apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-system-aggregate-to-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:aggregate-to-view
subjects:
- kind: ServiceAccount
  name: argo-workflow
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-argo-rollouts-aggregate-to-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-rollouts-aggregate-to-view
subjects:
- kind: ServiceAccount
  name: argo-workflow
  namespace: default
