apiVersion: v1
data:
  tempo-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Tempo
      type: tempo
      orgId: 1
      url: http://tempo:3100
      basicAuth: false
      version: 1
      editable: false
      apiVersion: 1
      uid: tempo
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: "1"
  name: tempo-grafana-datasource
  namespace: observability
---