{
 "title": "Hello Service Health",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Blackbox Probe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(status) (count_values(\"status\", probe_http_status_code{target=\"hello\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blackbox Nines",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{target=\"hello\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Impact",
   "type": "stat",
   "description": "The load simulator simulates real users making queries against the service. This Metric is the rate of successful queries in the specified interval",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(sum(k6_http_reqs_total{status=\"200\"})[$__range:$__rate_interval])/\nsum_over_time(sum(k6_http_reqs_total)[$__range:$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}