services:
  registry_docker_io:
    image: registry:latest
    ports:
      - 5001:5000
    volumes:
      - registry_docker_io:/var/lib/registry
    environment:
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
  registry_quay_io:
    image: registry:latest
    ports:
      - 5002:5000
    volumes:
      - registry_quay_io:/var/lib/registry
    environment:
      REGISTRY_PROXY_REMOTEURL: https://quay.io

volumes:
  registry_quay_io:
  registry_docker_io: