serviceMonitor:
  enabled: true
  selfMonitor:
    enabled: true
  targets:
    - name: hello
      url: https://host.k3d.internal/
      additionalRelabeling:
        - sourceLabels: [target]
          targetLabel: __param_hostname
          replacement: hello.k3d.localhost
      interval: 1s
      scrapeTimeout: 1s
      module: http_2xx
extraConfigmapMounts:
  - name: certificate-host-k3d-internal
    mountPath: /etc/ssl/certs/host.k3d.internal
    subPath: host.k3d.internal.crt
    configMap: certificate-host.k3d.internal
    readOnly: true
