---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  registry.server: |
    registry.k3d.local.profitbricks.net:53 {
      rewrite name registry.k3d.local.profitbricks.net registry
      forward . 127.0.0.1
    }
