ports:
  web:
    redirectTo: websecure
tlsStore:
  default:
    defaultCertificate:
      secretName: tls-default-certificate
      
metrics:
  prometheus:
    service:
      enabled: true
    serviceMonitor:
      namespace: "observability"
