deployment:
  podAnnotations:
    linkerd.io/inject: ingress
ports:
  web:
    redirectTo: websecure
tlsStore:
  default:
    defaultCertificate:
      secretName: tls-default-certificate
logs:
  format: json
  general:
    format: json
    level: INFO
  access:
    enabled: true
    format: json
metrics:
  prometheus:
    service:
      enabled: true
    serviceMonitor:
      namespace: "observability"
tracing:
  jaeger:
    collector:
      endpoint: http://tempo.observability.svc.cluster.local:14268/api/traces
