apiVersion: v1
kind: ConfigMap
metadata:
  name: load-simulation-script
data:
  script.js: |-
    import http from "k6/http";
    import { sleep } from "k6";

    const API_BASE_URL = 'http://hello-root.default.traefik.mesh';
    const params = {
      headers: {
      }
    }

    export const options = {
      insecureSkipTLSVerify: true
    }

    export default function () {
      http.batch([["GET", `${API_BASE_URL}/`, null, params]]);

      sleep(1);
    }

---
apiVersion: batch/v1
kind: Job
metadata:
  name: load-simulation
spec:
  parallelism: 1
  completions: null
  template:
    metadata:
      name: load-simulation
    spec:
      restartPolicy: Never
      containers:
      - name: k6
        image: grafana/k6
        args: ["run", "-u", "1000", "-d", "1000000h", "--no-thresholds", "/mnt/scripts/script.js"]
        volumeMounts:
        - mountPath: /mnt/scripts
          name: scripts
      volumes:
      - name: scripts
        configMap:
          name: load-simulation-script
